### ISSUE TITLE
UI doesnot get detected in the  image

### ISSUE THREAD

**Issue by Helaly96** [yasirkula/Unity360ScreenshotCapture#10]
**Description of the bug**

After using the plugin (thank you!) it gives amazing results, but all the UI elements (canvas-buttons-panels) do not get added to the screenshot itself.

**Reproduction steps**

add UI to the scene and screenshot using test example.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2019.3.5f1*
- Platform: *e.g. Android, iOS, Windows*

**Comment by yasirkula** [comment]
Please see #1
