### ISSUE TITLE
Blue camera

### ISSUE THREAD

**Issue by Vaxela** [yasirkula/Unity360ScreenshotCapture#2]
Camera settings base
360 photos
![screen_360_2018-06-25_15-54-50](https://user-images.githubusercontent.com/32814462/41854363-57c6fbac-7890-11e8-8b9b-1dbbc1851031.jpeg)

no 360
![screen_3840x2160_2018-06-25_15-31-46](https://user-images.githubusercontent.com/32814462/41854380-60f7e560-7890-11e8-9d5b-ef9af6e32645.jpg)

Unity 2018.1.5f1

No problem with unity 2017

**Comment by yasirkula** [comment]
On 2018.1.3f1, I've tried the plugin on a new scene with the example code and it worked correctly for me. I didn't change any parameters of the scene after creating it. Does it still not work for you on a new scene, using the example code?

**Comment by Vaxela** [comment]
Ok its good in new scene and with your test script in my scene, 
it comes from me you can close the subject I will find my mistakes , thanks 👍
