### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/Unity360ScreenshotCapture#7]
![image](https://user-images.githubusercontent.com/50401776/63633704-03e50e00-c67f-11e9-9610-df05cae86581.png)
This is my scene
![image](https://user-images.githubusercontent.com/50401776/63633717-27a85400-c67f-11e9-8d5e-b3843c35a2c3.png)
This is the panorama I rendered.
What problem have you seen?
The ground of my scene uses a mirror-like material
I don't know why this kind of problem occurs. My guess is probably the ground shader.
![image](https://user-images.githubusercontent.com/50401776/63633791-4bb86500-c680-11e9-9c66-e85e3193d737.png)

**Comment by yasirkula** [comment]
I think you are right. Please see: https://forum.unity.com/threads/360-screenshot-capture-open-source.501310/#post-4889699

**Comment by yasirkula** [comment]
Solution: https://forum.unity.com/threads/360-screenshot-capture-open-source.501310/#post-7078093
